### ISSUE TITLE
Text primitive is terribly buggy

### ISSUE THREAD

**Issue by bryik** [bryik/aframe-bmfont-text-component#10]
Thing I've noticed: 
- color failing to override default (text is black regardless of color attribute)
- mixing text primitive and regular a-entity with bmfont-text component fails sometimes (primitive will not appear)
- multiple text primitives in a single scene can cause some or all text to not appear

Using [play() instead of update()](https://github.com/donmccurdy/aframe-extras/blob/master/src/primitives/a-ocean.js#L44) does help with the first issue. However, it breaks setAttribute?

**Comment by donmccurdy** [comment]
1 and 2 sound a lot like https://github.com/aframevr/aframe/issues/1900

**Comment by bryik** [comment]
Yeah, you're right. I'll be keeping an eye on that issue.

**Comment by bryik** [comment]
Seems to be fixed with A-Frame v0.4.0.
