### ISSUE TITLE
Helvetica as default

### ISSUE THREAD

**Issue by joelnz** [bryik/aframe-bmfont-text-component#11]
Might save time for people wanting something neutral. 
Great plugin!

**Comment by joelnz** [comment]
Or just provide a link to helvetica.fnt & helvetica.png files?

**Comment by bryik** [comment]
Is Helvetica in the public domain? Distributing it might be an issue (this is the reason I didn't add Arial black).

It's a good idea though.

**Comment by bryik** [comment]
Closing as this issue has been open for quite some time and I'm about to archive this project.

Helvetica is decidedly [not in the public domain](https://www.linotype.com/1308886/helvetica-family.html). A-Frame's built-in text component [defaults to Roboto](https://aframe.io/docs/1.0.0/components/text.html#fonts) which is a pretty good default IMO.
