### ISSUE TITLE
Handle updates more performantly

### ISSUE THREAD

**Issue by ngokevin** [bryik/aframe-bmfont-text-component#16]
For example, if we tween properties such as `opacity`, it will re-create the text from scratch.

**Comment by bryik** [comment]
Yep, this could be done better. 

Changing shader uniforms in an active scene (e.g. with devtools) doesn't do anything for some reason.

**Comment by ngokevin** [comment]
Have you tried `material.needsUpdate`?

**Comment by bryik** [comment]
Closing as this issue has been open for quite some time and I'm about to archive this project.

Not sure why I never responded to this, sorry!
