### ISSUE TITLE
Embedding in Wordpress

### ISSUE THREAD

**Issue by VRPlayhouse** [bryik/aframe-bmfont-text-component#17]
I am attempting to embed an aframe scene into my wordpress template, but so far I have had no luck. I keep getting an error "Cannot read property 'removeBehavior' of null". I saw an earlier issue that mentioned rocketscript breaking the javascript so I did a bit of research and added code to functions.php to disable rocketscript loading for the aframe.min.js script. This didn't fix anything sadly. I get the error 5 times when the page loads, it is reported from material.js file at line 79:

if (Object.keys(tickProperties).length === 0) {

```
  scene.removeBehavior(this);

}
```

Does anyone have any input on this? It looks to me that scene is not being set correctly.

The code I am embedding is just the hello world stuff straight from the a-frame site:

<a-scene>

```
  <a-sphere position="0 1.25 -1" radius="1.25" color="#EF2D5E"></a-sphere>

  <a-box position="-1 0.5 1" rotation="0 45 0" width="1" height="1" depth="1"  color="#4CC3D9">
```

</a-box>

```
  <a-cylinder position="1 0.75 1" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>

  <a-plane rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>

  <a-sky color="#ECECEC"></a-sky>

  <a-entity position="0 0 3.8">

    <a-camera></a-camera>

  </a-entity>
```

</a-scene>

**Comment by bryik** [comment]
Maybe post this on [StackOverflow under the "aframe" tag](http://stackoverflow.com/questions/tagged/aframe)? Not sure what this has to do with bmfont-text specifically...

Let me know if I've missed something in your post.
