### ISSUE TITLE
Animating opacity crashes WebGL after looping a few times

### ISSUE THREAD

**Issue by ghost** [bryik/aframe-bmfont-text-component#19]
Adding the following animation as a child of the bmfont-text component causes webGL to crash with 

> 'GL_INVALID_OPERATION: glGenSyncTokenCHROMIUM: fence sync must be flushed before generating sync token'

followed by 

> 'WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost'

and 'THREE.WebGLShader: gl.getShaderInfoLog() vertex null 1: precision highp float;

`<a-animation
						attribute="bmfont-text.opacity"
						from="0.8"
						to="0.3"
						dur="500"
						repeat="indefinite"
						easing="linear"
						direction="alternate">
					</a-animation>`

For me it crashes after ~45 seconds.

![webgl-snag](https://cloud.githubusercontent.com/assets/22797595/20143852/816fab9c-a692-11e6-95a0-8591a524453d.png)

**Comment by bryik** [comment]
Interesting. I knew the implementation was inefficient, but didn't know it could cause a crash.

[Stats show textures and geometries increase with every animation](https://codepen.io/bryik/pen/ObyvbY), I guess old text is not being removed from the scene? I couldn't get it to crash, but [the same animation with geometric text](https://codepen.io/bryik/pen/ENVEgv) does not show increments in geometries.

**Comment by bryik** [comment]
Closing as this issue has been open for quite some time and I'm about to archive this project.

Although I'm somewhat curious to know if `<a-text>` suffers from this problem.
