### ISSUE TITLE
Way to cache fntImage?

### ISSUE THREAD

**Issue by ehknight** [bryik/aframe-bmfont-text-component#24]
Is there a way to use an earlier asset without having to fetch a new fntImage every time a bmfont text is used? For example, would it be possible to have fntImage point to something in <a-assets>?

**Comment by bryik** [comment]
Point to something in what? [A-assets](https://aframe.io/docs/0.4.0/core/asset-management-system.html)?

The default fntImage should be cached.

**Comment by ehknight** [comment]
Sorry for not being clear; I'm wondering if there is a way to avoid [this situation](http://imgur.com/a/PCmRQ). Or is this cached as well?

**Comment by bryik** [comment]
To be honest, I have not looked into how caching actually works internally...but now I'm curious. 

The files in the three.js cache can be found with `window.AFRAME.THREE.Cache.files`. Try running that in the console and checking if futura.png is there.

**Comment by ehknight** [comment]
Yup, looks like it was cached! Will close.

<img width="372" alt="screen shot 2016-12-28 at 11 37 37 pm" src="https://cloud.githubusercontent.com/assets/15150351/21538878/532751aa-cd56-11e6-99ae-8d84e5d8076d.png">
