### ISSUE TITLE
THREE.WebGLShader: Shader couldn't compile.

### ISSUE THREAD

**Issue by frabaglia** [bryik/aframe-bmfont-text-component#28]
Hi.

Some Android phones, as Galaxy S5 Mini, throws this exeption on runetime:

```
THREE.WebGLShader: Shader couldn't compile.
WebGLShader @ aframe.js:37965
WebGLProgram @ aframe.js:37454
acquireProgram @ aframe.js:37868
initMaterial @ aframe.js:34193
setProgram @ aframe.js:34357
renderBufferDirect @ aframe.js:33358
renderObjects @ aframe.js:34125
render @ aframe.js:33882
render @ aframe.js:66733
value @ aframe.js:62886
aframe.js:37488 THREE.WebGLProgram: shader error: 0 gl.VALIDATE_STATUS false gl.getProgramInfoLog invalid shaders ERROR: 0:4: 'highp' : precision is not supported in fragment shader

WebGLProgram @ aframe.js:37488
acquireProgram @ aframe.js:37868
initMaterial @ aframe.js:34193
setProgram @ aframe.js:34357
renderBufferDirect @ aframe.js:33358
renderObjects @ aframe.js:34125
render @ aframe.js:33882
render @ aframe.js:66733
value @ aframe.js:62886
```

Actually i really don't need to fix the bug, but in first, at least make some programatically test. So i decided to make some like this:

```
function pixelShaderSupport() {
  console.log("Checking pixel shader...");
  var support = true;
  try {
    var textTry = '<a-scene><a-entity style="display: none;" class="animate" id="textTry" rotation="0 0 0" scale="1 1 1" position="1 1 1" bmfont-text="color: white; mode: pre; text: tmp" look-at="[camera]"></a-entity></a-scene>';
    $('body').append(textTry);
  } catch (error) {
    if (error)
      {
        console.log("Your device doesn't support the bmfont-text shader...");
        support = false;
      }
  }
  return support;
}
```

But is not throwing, i think because the shader itself is not running.

Any way to fix or to prevent test this exception?

Thanks,

**Comment by bryik** [comment]
According to MDN, ["Using highp precision in fragment shaders will prevent your content from working on some older mobile hardware. You can use mediump instead, but be aware that this often results in corrupted rendering due to lack of precision on most mobile devices, and the corruption is not going to be visible on a typical desktop computer"](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices).

MDN also says that there is a function ["getShaderPrecisionFormat()"](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getShaderPrecisionFormat) that can check if highp precision is supported.

So I guess you'd need to fork the component and add some code that tests if highp precision is supported. You could also try using mediump instead of highp (although this may result in degraded quality or corruption).

**Comment by frabaglia** [comment]
Hi!

I made this test on early stage on my app to, in case of, redirect the user to a limited experience version:

```
function pixelShader() {
  var support = true;
  try {
    var canvas = document.getElementsByTagName('canvas')[0]
    var gl = canvas.getContext("webgl")
    var shaderType = [gl.VERTEX_SHADER,gl.FRAGMENT_SHADER]
    var precisionType = [gl.LOW_FLOAT, gl.MEDIUM_FLOAT, gl.HIGH_FLOAT, gl.LOW_INT, gl.MEDIUM_INT, gl.HIGH_INT]
    shaderType.forEach(function(shader){
      precisionType.forEach(function(precision){
        gl.getShaderPrecisionFormat(shader,precision)
      })
    })
  } catch (error) {
    if (error)
      {
        support = false;
      }
  }
  return support;
}
```

Where do you think i could integrate this in your component? Let me try and if it looks fine i'll send you a PR.

**Comment by bryik** [comment]
Changing the precision used by the fragment shader can be done by adding a parameter [here](https://github.com/bryik/aframe-bmfont-text-component/blob/master/index.js#L92). Try testing with `precision: "mediump"`.

```js
var material = new THREE.RawShaderMaterial(SDFShader({
    precision: "mediump",
    map: texture,
    side: THREE.DoubleSide,
    transparent: true,
    color: data.color,
    opacity: data.opacity
}));
```
If that fixes the problem on mobile let me know and I'll try to help with integrating the test.

P.S.
I've just discovered that Three.js' WebGL renderer has a "capabilities" property that contains a method [getMaxPrecision()](https://github.com/mrdoob/three.js/blob/6c7f000734f8579da37fb39e5c2e9e5e2dfb14f8/src/renderers/webgl/WebGLCapabilities.js#L29). Might be useful.

**Comment by bryik** [comment]
Closing as this issue has been open for quite some time and I'm about to archive this project.
