### ISSUE TITLE
can this support Chinese?How?

### ISSUE THREAD

**Issue by renwuming** [bryik/aframe-bmfont-text-component#7]

**Comment by bryik** [comment]
> SDF works great when you have a font that supports all the characters you need. The manual nature of SDF means there is no font stack. This means if the user gives us some fancy unicode character that isn’t in our main font then we can’t render it. - [Parris Khachi](https://www.eventbrite.com/engineering/its-2015-and-drawing-text-is-still-hard-webgl-threejs/)

It might be possible to create a Chinese character font. The process should be similar to making an English font. There might be issues with handling tens of thousands of characters.

For those interested: [The Complete Beginner’s Guide to Chinese Fonts](http://webdesign.tutsplus.com/articles/the-complete-beginners-guide-to-chinese-fonts--cms-23444)

Edit:

I looked into it a bit more; from [StackExchange](http://gamedev.stackexchange.com/questions/81401/how-do-games-handle-rendering-asian-unicode-text):

> In the games I've worked on, we restricted the subset of characters used for Chinese, Japanese, and Korean (together referred to as CJK) to only those required to display the text in the game.
> 
> In other words, we didn't attempt to cram in every possible character; we just took the database of CJK text from our localization teams, did a pass over it to find all the Unicode code points that occurred at least once in the text, and generated a BMFont configuration file to lay out an atlas for exactly those characters. (It was all automated, so every time we got a new loc drop, we could regenerate the list of characters and the fonts as needed.)

**Comment by bryik** [comment]
Mattdesl has said [non-Latin languages are outside the scope of three-bmfont](https://github.com/Jam3/three-bmfont-text/issues/11), so unfortunately this cannot be supported.
